sudo: required

services:
  - docker
language: python
python: '2.7'
script: python manage.py test
before_install:
- docker pull dnhsoft/mysql-utf8
- docker run --name XCX-mysql -e MYSQL_ROOT_PASSWORD=1234569 -e MYSQL_DATABASE=XCX -p 3306:3306 -d dnhsoft/mysql-utf8:latest
- docker ps -a
install:
- pip install -r requirements.txt
- sudo apt-get install zip -y
- sudo apt-get install sshpass -y
after_success:
- export SSHPASS=$DEPLOY_PASSWORD

- sshpass -e ssh  -o stricthostkeychecking=no ubuntu@123.206.60.123 "cd /var/www/XCX/&&sudo git pull&&sudo touch reload"

env:
  global:
    secure: APcz/dbL2vy2cwPCjYTMKDd86An1b3v8OYtvEfBJTJ7qynDjSGj3eHSdLtrdL61ioM8bkbUqMSBU3NcgHzJ4KA5dDCcxMiGuMR4JOB1NWTKYF3KIWn8nfYwDJ110QO63oyvB+cdReij2cKrm1FJfxtUnB+G3VueNI39o4oC4UFGsLtP2nneF0WqSdyOpjAYLBcyilB4v/tN1YHuKK16HPm8MUI5S2jZQ41QwRD2IKCkNXLH+V3GKyrXIFqKyN2O81aOMm5fvQuIUyNCTUeUtg+oJ2QoZoSaePagjwar1g5Hn55ywBGd6u7ZNyKe1+1xjQDJ1aIbEWQiFV/G90szmciLBDkRQXxQ/UZNoJOdz9qrOZTtLvBqjkdrZikltKU0yLNreDXQqrc+H5/eIo7ZTNUXv6qAv78+AqCQMKCsd32W3Pf7lq+pmoWpvBklGBWLQ9wCWJa3GQD1QWaZJ7bCdL/J41IsmqOez6CIeutZN8E67EgpTgod8EZRFG7vEmcrhQt+FjsM3QbQECGNRl7f5vfuJb9FSKZxQz8X4Lo4aIKvOSat2V+iOfiNe3YkPA0OY5EeNrZnlTPGTYj8zqszvU29OWSFSTmIF1KrxcaCJ9d6qpO0hhFiVpcYz68izFxUdvCdaiiSPsL1OMEaW3FybxUmHktylNwDqPZHE/QbZUYw=
